/* eslint-disable */
/**
 * GENERATED by scripts/gen-data-types.mjs from schemas/app-release-v1.schema.json.
 * Do not edit: change the schema and run `npm run data:types`.
 */

/**
 * A full 40-character git commit SHA. Short SHAs are a display concern, never stored.
 */
export type GitRevision = string;
export type Path = string;
/**
 * sha256 of the exact payload bytes fetched from the source.
 */
export type Digest = string;

/**
 * The record of one application release (#11), stored at releases/app/<release>/release.json next to its renderer artifact and never rewritten: the renderer module and HTML template a content release renders with, and every hashed asset under assets/ the rendered HTML may reference, each with its digest. A content publish resolves the deployed release from /current.json, verifies this record's digest, then every renderer file and the presence of every asset, before it renders anything.
 */
export interface AppReleaseV1 {
  $schema?: string;
  schemaVersion: 'app-release-v1';
  release: GitRevision;
  repository: 'redact-secret/redact-secret-www';
  /**
   * The renderer interface version (src/render.tsx rendererApi).
   */
  rendererApi: number;
  renderer: Path;
  template: Path;
  /**
   * The renderer artifact's files, relative to the release root.
   *
   * @minItems 2
   */
  files: [ReleaseFile, ReleaseFile, ...ReleaseFile[]];
  /**
   * Every hashed asset of the release, bucket-relative (assets/…).
   *
   * @minItems 1
   */
  assets: [ReleaseFile, ...ReleaseFile[]];
}
export interface ReleaseFile {
  path: Path;
  digest: Digest;
  bytes: number;
}
