/* eslint-disable */
/**
 * GENERATED by scripts/gen-data-types.mjs from schemas/content-manifest-v1.schema.json.
 * Do not edit: change the schema and run `npm run data:types`.
 */

/**
 * sha256 of the exact payload bytes fetched from the source.
 */
export type Digest = string;
/**
 * A full 40-character git commit SHA. Short SHAs are a display concern, never stored.
 */
export type GitRevision = string;
export type Source = RepositorySource | RegistrySource | AuthoredSource;
export type RepositoryName = string;
export type Registry = 'npm' | 'pypi' | 'crates';
/**
 * fresh: read from its source at observedAt. stale: the last refresh could not read the source, so the previous value is kept with its ORIGINAL observedAt (and staleSince records when that refresh failed). A stale value is never presented as fresh.
 */
export type Freshness = 'fresh' | 'stale';

/**
 * One locale's content release (#6 § First paint): which content and data files it consists of, their digests, the renderer release that renders them, and the upstream revisions they were read from. The release ID is content-addressed. Consumers fail closed on an unknown schemaVersion, a wrong locale, a missing file or a digest mismatch.
 */
export interface ContentManifestV1 {
  $schema?: string;
  schemaVersion: 'content-manifest-v1';
  releaseId: Digest;
  locale: 'en' | 'ko';
  rendererRelease: GitRevision;
  generatedAt: string;
  /**
   * Every upstream the content was read from, at its full revision.
   */
  sources: ManifestSource[];
  /**
   * @minItems 1
   */
  files: [ManifestFile, ...ManifestFile[]];
}
export interface ManifestSource {
  name: string;
  source: Source;
  freshness: Freshness;
  digest?: Digest;
}
/**
 * Files read from a git repository at one full revision.
 */
export interface RepositorySource {
  kind: 'repository';
  repository: RepositoryName;
  revision: GitRevision;
  /**
   * The product release that revision is, if it is one.
   */
  release?: string;
  /**
   * Files at that revision the value was read from.
   */
  paths?: string[];
}
/**
 * A package registry document. `version` is the published version the value describes; `revision` is that version's git commit when the registry records one (npm gitHead).
 */
export interface RegistrySource {
  kind: 'registry';
  registry: Registry;
  package: string;
  url: string;
  version?: string;
  revision?: GitRevision;
  repository?: RepositoryName;
  /**
   * Files inside the published package the value was read from.
   */
  paths?: string[];
}
/**
 * Authored and code-reviewed in this repository. Its revision is the commit that contains `path`; git history is the provenance.
 */
export interface AuthoredSource {
  kind: 'authored';
  repository: 'redact-secret/redact-secret-www';
  path: string;
}
export interface ManifestFile {
  /**
   * Relative to the release root; never absolute, never climbing out.
   */
  path: string;
  /**
   * The contract the file validates against.
   */
  schemaVersion: string;
  digest: Digest;
  bytes: number;
}
