/* eslint-disable */
/**
 * GENERATED by scripts/gen-data-types.mjs from schemas/content-current-v1.schema.json.
 * Do not edit: change the schema and run `npm run data:types`.
 */

/**
 * sha256 of the exact payload bytes fetched from the source.
 */
export type Digest = string;
/**
 * A full 40-character git commit SHA. Short SHAs are a display concern, never stored.
 */
export type GitRevision = string;

/**
 * /current.json: the pointer to the live content release and the application release it was rendered by (#11). Written last in a publish, with revalidation cache headers; a pure function of the release, so rolling back to a release restores it byte for byte. Public: it holds identifiers and digests only.
 */
export interface ContentCurrentV1 {
  $schema?: string;
  schemaVersion: 'content-current-v1';
  releaseId: Digest;
  manifest: ObjectRef;
  rendererRelease: GitRevision;
  app: ObjectRef;
}
export interface ObjectRef {
  path: string;
  digest: Digest;
}
