/* eslint-disable */
/**
 * GENERATED by scripts/gen-data-types.mjs from schemas/content-manifest-v2.schema.json.
 * Do not edit: change the schema and run `npm run data:types`.
 */

/**
 * sha256 of the exact payload bytes fetched from the source.
 */
export type Digest = string;
/**
 * A full 40-character git commit SHA. Short SHAs are a display concern, never stored.
 */
export type GitRevision = string;
export type Source = RepositorySource | RegistrySource | AuthoredSource;
export type RepositoryName = string;
export type Registry = 'npm' | 'pypi' | 'crates';
/**
 * fresh: read from its source at observedAt. stale: the last refresh could not read the source, so the previous value is kept with its ORIGINAL observedAt (and staleSince records when that refresh failed). A stale value is never presented as fresh.
 */
export type Freshness = 'fresh' | 'stale';

/**
 * One content release of the whole site (#11): every locale's rendered HTML, the copy and data it was rendered from, their digests, the application release whose renderer produced the HTML, and the full revisions of every source. Stored at content/<releaseId hex>/manifest.json next to the files it lists, and never rewritten. v2 replaces the per-locale v1: one release spans both locales and holds locale-neutral files (data/, the bilingual 404 page) and HTML, which v1 could not list. Consumers fail closed on an unknown schemaVersion, a locale set or file locale that does not match, a missing file, a digest mismatch, or a renderer release other than the deployed one.
 */
export interface ContentManifestV2 {
  $schema?: string;
  schemaVersion: 'content-manifest-v2';
  releaseId: Digest;
  /**
   * Every locale the release renders; must be exactly the renderer's locales.
   *
   * @minItems 1
   */
  locales: ['en' | 'ko', ...('en' | 'ko')[]];
  rendererRelease: GitRevision;
  generatedAt: string;
  /**
   * Every source the content was read from, at its full revision: this repository's commit (`www`), each upstream feed recorded in data/release.json (`feeds/<name>`), and each source data/evidence.json cites (`evidence/<name>`).
   *
   * @minItems 1
   */
  sources: [ManifestSource, ...ManifestSource[]];
  /**
   * @minItems 1
   */
  files: [ManifestFile, ...ManifestFile[]];
}
export interface ManifestSource {
  name: string;
  source: Source;
  freshness: Freshness;
  digest?: Digest;
}
/**
 * Files read from a git repository at one full revision.
 */
export interface RepositorySource {
  kind: 'repository';
  repository: RepositoryName;
  revision: GitRevision;
  /**
   * The product release that revision is, if it is one.
   */
  release?: string;
  /**
   * Files at that revision the value was read from.
   */
  paths?: string[];
}
/**
 * A package registry document. `version` is the published version the value describes; `revision` is that version's git commit when the registry records one (npm gitHead).
 */
export interface RegistrySource {
  kind: 'registry';
  registry: Registry;
  package: string;
  url: string;
  version?: string;
  revision?: GitRevision;
  repository?: RepositoryName;
  /**
   * Files inside the published package the value was read from.
   */
  paths?: string[];
}
/**
 * Authored and code-reviewed in this repository. Its revision is the commit that contains `path`; git history is the provenance.
 */
export interface AuthoredSource {
  kind: 'authored';
  repository: 'redact-secret/redact-secret-www';
  path: string;
}
export interface ManifestFile {
  /**
   * Relative to the release root (content/<releaseId hex>/): `html/<served path>index.html` for a page, `src/<repository path>` for a copy or data file. Never absolute, never climbing out.
   */
  path: string;
  /**
   * html: a rendered page, copied to its stable path when the release goes live. copy: i18n/<locale>/**.json. data: data/*.json.
   */
  kind: 'html' | 'copy' | 'data';
  /**
   * The locale the file is written in. Absent for data and for the 404 page, which speaks every locale.
   */
  locale?: 'en' | 'ko';
  /**
   * The contract a copy or data file validates against.
   */
  schemaVersion?: string;
  digest: Digest;
  bytes: number;
}
