/* eslint-disable */
/**
 * GENERATED by scripts/gen-data-types.mjs from schemas/evidence-v1.schema.json.
 * Do not edit: change the schema and run `npm run data:types`.
 */

/**
 * ISO 8601. A full date-time when a script recorded it; a calendar date when a maintainer read the source by hand and no finer time was recorded.
 */
export type Timestamp = string;
export type RepositoryName = string;
/**
 * A full 40-character git commit SHA. Short SHAs are a display concern, never stored.
 */
export type GitRevision = string;
export type Registry = 'npm' | 'pypi' | 'crates';
/**
 * fresh: read from its source at observedAt. stale: the last refresh could not read the source, so the previous value is kept with its ORIGINAL observedAt (and staleSince records when that refresh failed). A stale value is never presented as fresh.
 */
export type Freshness = 'fresh' | 'stale';
/**
 * A key of `sources`.
 */
export type FactSource = 'core' | 'benchmarks' | 'adapters' | 'vault';
/**
 * Files at that source's revision the value was read or computed from.
 *
 * @minItems 1
 */
export type FactPaths = [string, ...string[]];
/**
 * A provenance caveat a reviewer should see (not rendered).
 */
export type FactNote = string;
/**
 * A count or a limit. Integers only: a rate or a score is never stored here.
 */
export type Count = number;

/**
 * data/evidence.json: the counts, limits and names the /architecture/ pages cite, each fact tied to a named source at a full revision. Counts, limits and identifiers only: benchmark scores, rates and bounds stay owned by redact-secret-benchmarks and are never stored here, which is why every number in this schema is an integer.
 */
export interface EvidenceV1 {
  $schema?: string;
  schemaVersion: 'evidence-v1';
  observedAt: Timestamp;
  sources: {
    core: EvidenceSource;
    benchmarks: EvidenceSource;
    adapters: EvidenceSource;
    vault: EvidenceSource;
  };
  facts: {
    matrix: MatrixFact;
    taxonomy: TaxonomyFact;
    staleProse: StaleProseFact;
    baseline: BaselineFact;
    detectors: DetectorsFact;
    coreLimits: CoreLimitsFact;
    adapterBudgets: AdapterBudgetsFact;
  };
}
/**
 * A named source the facts cite, at one full revision, with when it was read and whether that reading is still current.
 */
export interface EvidenceSource {
  /**
   * A registry source must pin the version, its git revision and its repository.
   */
  source: RepositorySource | RegistrySource;
  observedAt: Timestamp;
  freshness: Freshness;
  staleSince?: Timestamp;
}
/**
 * Files read from a git repository at one full revision.
 */
export interface RepositorySource {
  kind: 'repository';
  repository: RepositoryName;
  revision: GitRevision;
  /**
   * The product release that revision is, if it is one.
   */
  release?: string;
  /**
   * Files at that revision the value was read from.
   */
  paths?: string[];
}
/**
 * A package registry document. `version` is the published version the value describes; `revision` is that version's git commit when the registry records one (npm gitHead).
 */
export interface RegistrySource {
  kind: 'registry';
  registry: Registry;
  package: string;
  url: string;
  version?: string;
  revision?: GitRevision;
  repository?: RepositoryName;
  /**
   * Files inside the published package the value was read from.
   */
  paths?: string[];
}
/**
 * The support matrix the core release ships (redact-secret docs/support-matrix.md, generated).
 */
export interface MatrixFact {
  source: FactSource;
  paths?: FactPaths;
  note?: FactNote;
  value: MatrixCounts;
}
export interface MatrixCounts {
  families: Count;
  providers: Count;
  status: StatusCounts;
  stableBasis: StableBasisCounts;
  tiers: TierCounts;
}
export interface StatusCounts {
  stable: Count;
  unsupported: Count;
  provisional: Count;
  pending: Count;
}
export interface StableBasisCounts {
  documented: Count;
  empirical: Count;
}
export interface TierCounts {
  T1: Count;
  T2: Count;
  T3: Count;
  T0: Count;
}
/**
 * The live taxonomy (redact-secret-benchmarks benchmarks/support/taxonomy.json). Counts only.
 */
export interface TaxonomyFact {
  source: FactSource;
  paths?: FactPaths;
  note?: FactNote;
  value: TaxonomyCounts;
}
export interface TaxonomyCounts {
  families: Count;
  providers: Count;
  withoutDetector: Count;
}
/**
 * What the taxonomy spec's prose still says, cited only as an example of prose going stale.
 */
export interface StaleProseFact {
  source: FactSource;
  paths?: FactPaths;
  note?: FactNote;
  value: StaleProseCounts;
}
export interface StaleProseCounts {
  families: Count;
  providers: Count;
  dated: string;
}
/**
 * The name of the frozen regression baseline (baselines/<name>.json). A name, never its contents.
 */
export interface BaselineFact {
  source: FactSource;
  paths?: FactPaths;
  note?: FactNote;
  value: string;
}
/**
 * Mechanism counts from the core source.
 */
export interface DetectorsFact {
  source: FactSource;
  paths?: FactPaths;
  note?: FactNote;
  value: DetectorCounts;
}
export interface DetectorCounts {
  structural: Count;
  alphabets: Count;
}
/**
 * The core's default input and findings limits.
 */
export interface CoreLimitsFact {
  source: FactSource;
  paths?: FactPaths;
  note?: FactNote;
  value: CoreLimits;
}
export interface CoreLimits {
  inputMiB: Count;
  findings: Count;
}
/**
 * The adapter walker's DEFAULT_LIMITS.
 */
export interface AdapterBudgetsFact {
  source: FactSource;
  paths?: FactPaths;
  note?: FactNote;
  value: AdapterBudgets;
}
export interface AdapterBudgets {
  depth: Count;
  arrayLength: Count;
  objectKeys: Count;
  leaves: Count;
  stringChars: Count;
}
