/* eslint-disable */
/**
 * GENERATED by scripts/gen-data-types.mjs from schemas/integrations-v1.schema.json.
 * Do not edit: change the schema and run `npm run data:types`.
 */

/**
 * ISO 8601. A full date-time when a script recorded it; a calendar date when a maintainer read the source by hand and no finer time was recorded.
 */
export type Timestamp = string;
export type Source = RepositorySource | RegistrySource | AuthoredSource;
export type RepositoryName = string;
/**
 * A full 40-character git commit SHA. Short SHAs are a display concern, never stored.
 */
export type GitRevision = string;
export type Registry = 'npm' | 'pypi' | 'crates';
/**
 * fresh: read from its source at observedAt. stale: the last refresh could not read the source, so the previous value is kept with its ORIGINAL observedAt (and staleSince records when that refresh failed). A stale value is never presented as fresh.
 */
export type Freshness = 'fresh' | 'stale';
export type GroupEntry = CoreGroupEntry | RuntimeGroupEntry;
export type FactKind = 'version' | 'registries' | 'core' | 'host' | 'tag' | 'install';

/**
 * data/integrations.json: which packages the site lists and where each is published (the refresh input), and the integrations block's structure — which cards exist, in which group and runtime, backed by which package. No versions, dates, tags or ranges: those are release data (release-v1). No prose: each locale authors the words for a card id.
 */
export interface IntegrationsV1 {
  $schema?: string;
  schemaVersion: 'integrations-v1';
  generatedAt: Timestamp;
  source: Source;
  freshness: Freshness;
  staleSince?: Timestamp;
  packages: {
    [k: string]: PackageEntry | undefined;
  };
  /**
   * @minItems 1
   */
  groups: [GroupEntry, ...GroupEntry[]];
}
/**
 * Files read from a git repository at one full revision.
 */
export interface RepositorySource {
  kind: 'repository';
  repository: RepositoryName;
  revision: GitRevision;
  /**
   * The product release that revision is, if it is one.
   */
  release?: string;
  /**
   * Files at that revision the value was read from.
   */
  paths?: string[];
}
/**
 * A package registry document. `version` is the published version the value describes; `revision` is that version's git commit when the registry records one (npm gitHead).
 */
export interface RegistrySource {
  kind: 'registry';
  registry: Registry;
  package: string;
  url: string;
  version?: string;
  revision?: GitRevision;
  repository?: RepositoryName;
  /**
   * Files inside the published package the value was read from.
   */
  paths?: string[];
}
/**
 * Authored and code-reviewed in this repository. Its revision is the commit that contains `path`; git history is the provenance.
 */
export interface AuthoredSource {
  kind: 'authored';
  repository: 'redact-secret/redact-secret-www';
  path: string;
}
export interface PackageEntry {
  registry: Registry;
  name: string;
  /**
   * npm dist-tag the page installs from, when it is not `latest`.
   */
  tag?: string;
  /**
   * The same package on other registries.
   */
  also?: PackageMirror[];
  declared?: DeclaredPackageVersion;
}
export interface PackageMirror {
  registry: Registry;
  name: string;
}
/**
 * The version the package's repository declares, shown when its registry does not have it yet.
 */
export interface DeclaredPackageVersion {
  version: string;
  source: RepositorySource;
}
export interface CoreGroupEntry {
  id: 'core';
  /**
   * @minItems 1
   */
  cards: [CardEntry, ...CardEntry[]];
}
export interface CardEntry {
  /**
   * Copy key in each locale's integrations.cards.
   */
  id: string;
  /**
   * A key of `packages` (and of release.json packages).
   */
  slot: string;
  /**
   * Shown instead of the package name (a subpath or an extra).
   */
  display?: string;
  /**
   * @minItems 1
   */
  facts: [FactKind, ...FactKind[]];
  /**
   * For `host` on a Python extra: the extra's name.
   */
  extra?: string;
  /**
   * For `install`: the command, with {version} replaced by the slot's published version.
   */
  install?: string;
}
export interface RuntimeGroupEntry {
  id: 'adapters' | 'vault';
  runtimes: RuntimeCards;
}
export interface RuntimeCards {
  browser: CardEntry[];
  node: CardEntry[];
  python: CardEntry[];
}
