/* eslint-disable */
/**
 * GENERATED by scripts/gen-data-types.mjs from schemas/locale-architecture-overview-v1.schema.json.
 * Do not edit: change the schema and run `npm run data:types`.
 */

/**
 * The locale this file is authored for; it must match the file's directory (i18n/<locale>/).
 */
export type LocaleId = 'en' | 'ko';
/**
 * Rich text: a plain string, or a list of inline nodes rendered in order by src/components/ui/Rich.tsx.
 */
export type Rich = string | [Inline, ...Inline[]];
/**
 * One inline node. Each object node has exactly one tag key (b, em, code, span, br, a, var, status, dim, flag, placeholder) plus the attributes that tag allows.
 */
export type Inline =
  | string
  | StrongNode
  | EmphasisNode
  | CodeNode
  | SpanNode
  | LineBreakNode
  | RouteLinkNode
  | UrlLinkNode
  | VariableNode
  | StatusNode
  | DimNode
  | FlagNode
  | PlaceholderNode;
/**
 * An internal link target: a route ID from src/routes.ts (home, community, architecture, architecture/<page>, docs, docs/<page>), optionally followed by #<anchor> from src/content/shared.ts anchors; or #<anchor> alone for the current page. Resolved to /… or /ko/… in code.
 */
export type RouteRef = string;
/**
 * An external link: an absolute https URL with no credentials.
 */
export type HttpsUrl = string;
/**
 * Plain text: no markup, no variables. Used where the value may end up in an attribute.
 */
export type Text = string;

/**
 * i18n/<locale>/architecture/overview.json: the architecture hub (/architecture/) body in one locale. Page titles come from section.json; paths from the route registry.
 */
export interface LocaleArchitectureOverviewV1 {
  $schema?: string;
  schemaVersion: 'locale-architecture-overview-v1';
  locale: LocaleId;
  eyebrow: Rich;
  title: Rich;
  lede: Rich;
  claim: {
    line: Rich;
    sub: Rich;
  };
  groups: {
    engine: {
      eyebrow: Rich;
      title: Rich;
    };
    evidence: {
      eyebrow: Rich;
      title: Rich;
    };
    boundaries: {
      eyebrow: Rich;
      title: Rich;
    };
  };
  cards: {
    'how-it-works': {
      question: Rich;
      body: Rich;
    };
    detection: {
      question: Rich;
      body: Rich;
    };
    'support-claims': {
      question: Rich;
      body: Rich;
    };
    'evaluation-methods': {
      question: Rich;
      body: Rich;
    };
    adapters: {
      question: Rich;
      body: Rich;
    };
    vault: {
      question: Rich;
      body: Rich;
    };
  };
  repos: {
    eyebrow: Rich;
    title: Rich;
    lede: Rich;
    tableLabel: Text;
    head: Rich[];
    rows: {
      repo: Text;
      owns: Rich;
      mustNot: Rich;
    }[];
  };
  sources: {
    label: Rich;
    body: Rich;
  };
}
/**
 * <b>
 */
export interface StrongNode {
  b: Rich;
}
/**
 * <em>
 */
export interface EmphasisNode {
  em: Rich;
}
/**
 * <code>
 */
export interface CodeNode {
  code: Rich;
}
/**
 * <span> with one of the global type classes (src/style.css).
 */
export interface SpanNode {
  span: Rich;
  class: 'mono' | 'tiny' | 'small' | 'tiny mono';
}
/**
 * <br>: an authored line break (hero and other large headlines break at an explicit point per locale).
 */
export interface LineBreakNode {
  br: true;
}
/**
 * <a> to a page on this site, in the page's own locale.
 */
export interface RouteLinkNode {
  a: Rich;
  to: RouteRef;
}
/**
 * <a> to an external https URL.
 */
export interface UrlLinkNode {
  a: Rich;
  href: HttpsUrl;
}
/**
 * A value supplied by the page at render time: a slot (version, date, count) or a fragment the page composes. Never typed into prose (CONVENTIONS.md § Content slots).
 */
export interface VariableNode {
  var: string;
}
/**
 * A status chip (src/components/ui/StatusChip.tsx) inside a sentence.
 */
export interface StatusNode {
  status: Rich;
  tone: 'success' | 'warning' | 'danger' | 'info' | 'none';
}
/**
 * A dimmed span inside a code sample (RichCode's Dim).
 */
export interface DimNode {
  dim: Rich;
}
/**
 * A flagged span inside a code sample (RichCode's Flag).
 */
export interface FlagNode {
  flag: Rich;
}
/**
 * A typed placeholder chip (src/components/ui/PlaceholderChip.tsx), e.g. <SECRET_1>.
 */
export interface PlaceholderNode {
  placeholder: Rich;
}
