/* eslint-disable */
/**
 * GENERATED by scripts/gen-data-types.mjs from schemas/locale-architecture-adapters-v1.schema.json.
 * Do not edit: change the schema and run `npm run data:types`.
 */

/**
 * The locale this file is authored for; it must match the file's directory (i18n/<locale>/).
 */
export type LocaleId = 'en' | 'ko';
/**
 * Plain text: no markup, no variables. Used where the value may end up in an attribute.
 */
export type Text = string;
/**
 * Rich text: a plain string, or a list of inline nodes rendered in order by src/components/ui/Rich.tsx.
 */
export type Rich = string | [Inline, ...Inline[]];
/**
 * One inline node. Each object node has exactly one tag key (b, em, code, span, br, a, var, status, dim, flag, placeholder) plus the attributes that tag allows.
 */
export type Inline =
  | string
  | StrongNode
  | EmphasisNode
  | CodeNode
  | SpanNode
  | LineBreakNode
  | RouteLinkNode
  | UrlLinkNode
  | VariableNode
  | StatusNode
  | DimNode
  | FlagNode
  | PlaceholderNode;
/**
 * An internal link target: a route ID from src/routes.ts (home, community, architecture, architecture/<page>, docs, docs/<page>), optionally followed by #<anchor> from src/content/shared.ts anchors; or #<anchor> alone for the current page. Resolved to /… or /ko/… in code.
 */
export type RouteRef = string;
/**
 * An external link: an absolute https URL with no credentials.
 */
export type HttpsUrl = string;

/**
 * i18n/<locale>/architecture/adapters.json: the words of the architecture page 'Adapters' in one locale, keyed by section in page order. The structure (components, diagrams, mechanism constants) is the page's template in src/pages/architecture/; counts, versions and commits are vars filled from the slots.
 */
export interface LocaleArchitectureAdaptersV1 {
  $schema?: string;
  schemaVersion: 'locale-architecture-adapters-v1';
  locale: LocaleId;
  statusLabels: {
    released: Text;
    alpha: Text;
    unpublished: Text;
  };
  head: {
    eyebrow: Text;
    title: Text;
    lede: Rich;
  };
  theProblemItSolves: {
    eyebrow: Text;
    title: Text;
    /**
     * null: this locale deliberately omits the element (authored per locale, CONVENTIONS.md § Bilingual content).
     */
    intro: Text | null;
    cards: {
      chip: Text;
      body: Rich;
    }[];
    outro: Rich;
  };
  whereTheySit: {
    eyebrow: Text;
    title: Text;
    nodeTitle1: Text;
    node1: Rich;
    arrow1: Rich;
    claimSub: Text;
    claim: Rich;
    arrow2: Rich;
    nodeTitle2: Text;
    node2: Rich;
  };
  thePackages: {
    eyebrow: Text;
    title: Text;
    tiles: Rich[];
    pythonMeta: Text;
    note: Rich;
    observed: Rich;
  };
  theDesignRule: {
    eyebrow: Text;
    title: Text;
    lede: Rich;
    markersLabel: Text;
    head: Text[];
    markers: Rich[];
    warning: Rich;
    budgetsHeading: Text;
    budgets: Text[];
    budgetsNote: Rich;
  };
  whyItStaysSmall: {
    eyebrow: Text;
    title: Text;
    rows: Rich[];
    p: Rich;
    note: Rich;
  };
  whatSupportedMeansHere: {
    eyebrow: Text;
    title: Text;
    lede: Rich;
    rangesLabel: Text;
    head: Text[];
    verifiedBy: Rich[];
    p: Rich;
  };
  beingHonest: {
    eyebrow: Text;
    title: Text;
    noteTitle: Text;
    items: Rich[];
  };
  sources: {
    label: Text;
    body: Rich;
    atCommit: Rich;
  };
}
/**
 * <b>
 */
export interface StrongNode {
  b: Rich;
}
/**
 * <em>
 */
export interface EmphasisNode {
  em: Rich;
}
/**
 * <code>
 */
export interface CodeNode {
  code: Rich;
}
/**
 * <span> with one of the global type classes (src/style.css).
 */
export interface SpanNode {
  span: Rich;
  class: 'mono' | 'tiny' | 'small' | 'tiny mono';
}
/**
 * <br>: an authored line break (hero and other large headlines break at an explicit point per locale).
 */
export interface LineBreakNode {
  br: true;
}
/**
 * <a> to a page on this site, in the page's own locale.
 */
export interface RouteLinkNode {
  a: Rich;
  to: RouteRef;
}
/**
 * <a> to an external https URL.
 */
export interface UrlLinkNode {
  a: Rich;
  href: HttpsUrl;
}
/**
 * A value supplied by the page at render time: a slot (version, date, count) or a fragment the page composes. Never typed into prose (CONVENTIONS.md § Content slots).
 */
export interface VariableNode {
  var: string;
}
/**
 * A status chip (src/components/ui/StatusChip.tsx) inside a sentence.
 */
export interface StatusNode {
  status: Rich;
  tone: 'success' | 'warning' | 'danger' | 'info' | 'none';
}
/**
 * A dimmed span inside a code sample (RichCode's Dim).
 */
export interface DimNode {
  dim: Rich;
}
/**
 * A flagged span inside a code sample (RichCode's Flag).
 */
export interface FlagNode {
  flag: Rich;
}
/**
 * A typed placeholder chip (src/components/ui/PlaceholderChip.tsx), e.g. <SECRET_1>.
 */
export interface PlaceholderNode {
  placeholder: Rich;
}
