/* eslint-disable */
/**
 * GENERATED by scripts/gen-data-types.mjs from schemas/locale-architecture-section-v1.schema.json.
 * Do not edit: change the schema and run `npm run data:types`.
 */

/**
 * The locale this file is authored for; it must match the file's directory (i18n/<locale>/).
 */
export type LocaleId = 'en' | 'ko';
/**
 * Plain text: no markup, no variables. Used where the value may end up in an attribute.
 */
export type Text = string;

/**
 * i18n/<locale>/architecture/section.json: the architecture section's shell copy in one locale — section name, sidebar groups, each page's navigation label, <title> and description, and the pager labels. Page order and grouping are the registry's (src/content/architecture/pages.ts), not the copy's.
 */
export interface LocaleArchitectureSectionV1 {
  $schema?: string;
  schemaVersion: 'locale-architecture-section-v1';
  locale: LocaleId;
  section: Text;
  navLabel: Text;
  contents: Text;
  groups: {
    section: Text;
    engine: Text;
    evidence: Text;
    boundaries: Text;
  };
  pages: {
    overview: {
      nav: Text;
      title: Text;
      description: Text;
    };
    'how-it-works': {
      nav: Text;
      title: Text;
      description: Text;
    };
    detection: {
      nav: Text;
      title: Text;
      description: Text;
    };
    'support-claims': {
      nav: Text;
      title: Text;
      description: Text;
    };
    'evaluation-methods': {
      nav: Text;
      title: Text;
      description: Text;
    };
    adapters: {
      nav: Text;
      title: Text;
      description: Text;
    };
    vault: {
      nav: Text;
      title: Text;
      description: Text;
    };
  };
  pager: {
    label: Text;
    prev: Text;
    next: Text;
    back: Text;
  };
}
