/* eslint-disable */
/**
 * GENERATED by scripts/gen-data-types.mjs from schemas/locale-architecture-detection-v1.schema.json.
 * Do not edit: change the schema and run `npm run data:types`.
 */

/**
 * The locale this file is authored for; it must match the file's directory (i18n/<locale>/).
 */
export type LocaleId = 'en' | 'ko';
/**
 * Plain text: no markup, no variables. Used where the value may end up in an attribute.
 */
export type Text = string;
/**
 * Rich text: a plain string, or a list of inline nodes rendered in order by src/components/ui/Rich.tsx.
 */
export type Rich = string | [Inline, ...Inline[]];
/**
 * One inline node. Each object node has exactly one tag key (b, em, code, span, br, a, var, status, dim, flag, placeholder) plus the attributes that tag allows.
 */
export type Inline =
  | string
  | StrongNode
  | EmphasisNode
  | CodeNode
  | SpanNode
  | LineBreakNode
  | RouteLinkNode
  | UrlLinkNode
  | VariableNode
  | StatusNode
  | DimNode
  | FlagNode
  | PlaceholderNode;
/**
 * An internal link target: a route ID from src/routes.ts (home, community, architecture, architecture/<page>), optionally followed by #<anchor> from src/content/shared.ts anchors; or #<anchor> alone for the current page. Resolved to /… or /ko/… in code.
 */
export type RouteRef = string;
/**
 * An external link: an absolute https URL with no credentials.
 */
export type HttpsUrl = string;

/**
 * i18n/<locale>/architecture/detection.json: the words of the architecture page 'How it detects' in one locale, keyed by section in page order. The structure (components, diagrams, mechanism constants) is the page's template in src/pages/architecture/; counts, versions and commits are vars filled from the slots.
 */
export interface LocaleArchitectureDetectionV1 {
  $schema?: string;
  schemaVersion: 'locale-architecture-detection-v1';
  locale: LocaleId;
  head: {
    eyebrow: Text;
    title: Text;
    lede: Text;
  };
  theLadder: {
    eyebrow: Text;
    title: Text;
    lede: Rich;
    rungs: {
      title: Text;
      sub: Rich;
    }[];
    axis: Text[];
  };
  tier4: {
    eyebrow: Text;
    title: Text;
    lede: Rich;
    parts: {
      desc: Rich;
    }[];
    rows: {
      term: Text;
      body: Rich;
    }[];
    p1: Rich;
    codeLabel: Text;
    code: Rich;
    p2: Rich;
    tradeoff: Rich;
  };
  tier3: {
    eyebrow: Text;
    title: Text;
    lede: Rich;
    rows: {
      term: Text;
      body: Rich;
    }[];
    p1: Rich;
    tradeoff: Rich;
  };
  tier2: {
    eyebrow: Text;
    title: Text;
    lede: Rich;
    rows: {
      term: Text;
      body: Rich;
    }[];
    heading: Rich;
    p1: Rich;
    chipsLabel: Text;
    p2: Rich;
    tradeoff: Rich;
  };
  tier1: {
    eyebrow: Text;
    title: Text;
    cards: {
      chip: Text;
      body: Rich;
    }[];
    claimSub: Text;
    claim: Rich;
  };
  whenTiersDisagree: {
    eyebrow: Text;
    title: Text;
    lede: Rich;
    rows: {
      term: Text;
      body: Rich;
    }[];
    p: Rich;
  };
  theLittleLanguage: {
    eyebrow: Text;
    title: Text;
    lede: Rich;
    cards: {
      title: Text;
      body: Rich;
    }[];
    alphabetsHeading: Rich;
    chipsLabel: Text;
  };
  bringYourOwnRules: {
    eyebrow: Text;
    title: Text;
    status: Text;
    lede: Rich;
    codeLabel: Text;
    cards: {
      title: Text;
      body: Rich;
    }[];
    rows: {
      term: Text;
      body: Rich;
    }[];
  };
  personalData: {
    eyebrow: Text;
    title: Text;
    lede: Rich;
    cards: {
      title: Text;
      body: Text;
    }[];
    p: Rich;
    note: Rich;
  };
  sources: {
    label: Text;
    body: Rich;
  };
}
/**
 * <b>
 */
export interface StrongNode {
  b: Rich;
}
/**
 * <em>
 */
export interface EmphasisNode {
  em: Rich;
}
/**
 * <code>
 */
export interface CodeNode {
  code: Rich;
}
/**
 * <span> with one of the global type classes (src/style.css).
 */
export interface SpanNode {
  span: Rich;
  class: 'mono' | 'tiny' | 'small' | 'tiny mono';
}
/**
 * <br>: an authored line break (hero and other large headlines break at an explicit point per locale).
 */
export interface LineBreakNode {
  br: true;
}
/**
 * <a> to a page on this site, in the page's own locale.
 */
export interface RouteLinkNode {
  a: Rich;
  to: RouteRef;
}
/**
 * <a> to an external https URL.
 */
export interface UrlLinkNode {
  a: Rich;
  href: HttpsUrl;
}
/**
 * A value supplied by the page at render time: a slot (version, date, count) or a fragment the page composes. Never typed into prose (CONVENTIONS.md § Content slots).
 */
export interface VariableNode {
  var: string;
}
/**
 * A status chip (src/components/ui/StatusChip.tsx) inside a sentence.
 */
export interface StatusNode {
  status: Rich;
  tone: 'success' | 'warning' | 'danger' | 'info' | 'none';
}
/**
 * A dimmed span inside a code sample (RichCode's Dim).
 */
export interface DimNode {
  dim: Rich;
}
/**
 * A flagged span inside a code sample (RichCode's Flag).
 */
export interface FlagNode {
  flag: Rich;
}
/**
 * A typed placeholder chip (src/components/ui/PlaceholderChip.tsx), e.g. <SECRET_1>.
 */
export interface PlaceholderNode {
  placeholder: Rich;
}
