/* eslint-disable */
/**
 * GENERATED by scripts/gen-data-types.mjs from schemas/locale-community-v1.schema.json.
 * Do not edit: change the schema and run `npm run data:types`.
 */

/**
 * The locale this file is authored for; it must match the file's directory (i18n/<locale>/).
 */
export type LocaleId = 'en' | 'ko';
/**
 * Plain text: no markup, no variables. Used where the value may end up in an attribute.
 */
export type Text = string;
/**
 * Rich text: a plain string, or a list of inline nodes rendered in order by src/components/ui/Rich.tsx.
 */
export type Rich = string | [Inline, ...Inline[]];
/**
 * One inline node. Each object node has exactly one tag key (b, em, code, span, br, a, var, status, dim, flag, placeholder) plus the attributes that tag allows.
 */
export type Inline =
  | string
  | StrongNode
  | EmphasisNode
  | CodeNode
  | SpanNode
  | LineBreakNode
  | RouteLinkNode
  | UrlLinkNode
  | VariableNode
  | StatusNode
  | DimNode
  | FlagNode
  | PlaceholderNode;
/**
 * An internal link target: a route ID from src/routes.ts (home, community, architecture, architecture/<page>, docs, docs/<page>), optionally followed by #<anchor> from src/content/shared.ts anchors; or #<anchor> alone for the current page. Resolved to /… or /ko/… in code.
 */
export type RouteRef = string;
/**
 * An external link: an absolute https URL with no credentials.
 */
export type HttpsUrl = string;

/**
 * i18n/<locale>/community.json: the community page's copy in one locale — the hero, the feedback kinds, the words around each form's fields, the in-browser check and hand-off to GitHub, and the private security route. The forms' field ids, types, options, labels and title prefixes are the prefill contract and live in src/content/community.ts, not here. Editorial; reviewed per locale; no versions, dates or counts (those are slots).
 */
export interface LocaleCommunityV1 {
  $schema?: string;
  schemaVersion: 'locale-community-v1';
  locale: LocaleId;
  meta: {
    title: Text;
    description: Text;
  };
  hero: {
    eyebrow: Text;
    title: Rich;
    lede: Rich;
    /**
     * @minItems 1
     */
    facts: [
      {
        lead: Text;
        body: Rich;
      },
      ...{
        lead: Text;
        body: Rich;
      }[]
    ];
  };
  kindsLabel: Text;
  groups: {
    wrong: Text;
    missing: Text;
    talk: Text;
    security: Text;
  };
  forms: {
    bug: FormCopy;
    'false-positive': FormCopy;
    'missed-detection': FormCopy;
    website: FormCopy;
    detector: FormCopy;
    integration: FormCopy;
    question: FormCopy;
    idea: FormCopy;
  };
  security: {
    name: Text;
    where: Text;
    title: Text;
    body: Rich;
    /**
     * @minItems 1
     */
    rules: [Rich, ...Rich[]];
    advisory: Text;
    policy: Text;
  };
  /**
   * Words every form shares.
   */
  form: {
    required: Text;
    optional: Text;
    choose: Text;
    titleLabel: Text;
    titleHelp: Rich;
    ackLegend: Text;
    issueForm: Text;
    discussion: Text;
    labels: Text;
    category: Text;
    source: Text;
    clear: Text;
    useTemplate: Text;
  };
  /**
   * The in-browser check and the hand-off to GitHub. Only idle and the blocked list are prerendered; the other states appear once a visitor types.
   */
  handoff: {
    title: Text;
    idle: Verdict;
    loading: Verdict;
    clean: Verdict;
    foundOne: Text;
    foundMany: Rich;
    foundBody: Rich;
    failed: Verdict;
    stale: Verdict;
    position: Rich;
    length: Rich;
    urlLabel: Text;
    urlLength: Rich;
    urlHidden: Text;
    go: Text;
    blockedBy: Text;
    needFields: Rich;
    needSafe: Text;
    needCheck: Text;
    needAck: Text;
    tooLong: Text;
    privacy: Rich;
    fallback: Text;
  };
  noscript: Rich;
  boundary: Rich;
}
/**
 * <b>
 */
export interface StrongNode {
  b: Rich;
}
/**
 * <em>
 */
export interface EmphasisNode {
  em: Rich;
}
/**
 * <code>
 */
export interface CodeNode {
  code: Rich;
}
/**
 * <span> with one of the global type classes (src/style.css).
 */
export interface SpanNode {
  span: Rich;
  class: 'mono' | 'tiny' | 'small' | 'tiny mono';
}
/**
 * <br>: an authored line break (hero and other large headlines break at an explicit point per locale).
 */
export interface LineBreakNode {
  br: true;
}
/**
 * <a> to a page on this site, in the page's own locale.
 */
export interface RouteLinkNode {
  a: Rich;
  to: RouteRef;
}
/**
 * <a> to an external https URL.
 */
export interface UrlLinkNode {
  a: Rich;
  href: HttpsUrl;
}
/**
 * A value supplied by the page at render time: a slot (version, date, count) or a fragment the page composes. Never typed into prose (CONVENTIONS.md § Content slots).
 */
export interface VariableNode {
  var: string;
}
/**
 * A status chip (src/components/ui/StatusChip.tsx) inside a sentence.
 */
export interface StatusNode {
  status: Rich;
  tone: 'success' | 'warning' | 'danger' | 'info' | 'none';
}
/**
 * A dimmed span inside a code sample (RichCode's Dim).
 */
export interface DimNode {
  dim: Rich;
}
/**
 * A flagged span inside a code sample (RichCode's Flag).
 */
export interface FlagNode {
  flag: Rich;
}
/**
 * A typed placeholder chip (src/components/ui/PlaceholderChip.tsx), e.g. <SECRET_1>.
 */
export interface PlaceholderNode {
  placeholder: Rich;
}
/**
 * One form's words. `fields` is keyed by the form's field ids in src/content/community.ts.
 */
export interface FormCopy {
  name: Text;
  where: Text;
  intro: Rich;
  fields: {
    [k: string]: FieldCopy | undefined;
  };
  ack: Text;
}
export interface FieldCopy {
  label: Text;
  help?: Rich;
  placeholder?: Rich;
  template?: Text;
}
export interface Verdict {
  verdict: Text;
  body: Rich;
}
