/* eslint-disable */
/**
 * GENERATED by scripts/gen-data-types.mjs from schemas/locale-home-v1.schema.json.
 * Do not edit: change the schema and run `npm run data:types`.
 */

/**
 * The locale this file is authored for; it must match the file's directory (i18n/<locale>/).
 */
export type LocaleId = 'en' | 'ko';
/**
 * Plain text: no markup, no variables. Used where the value may end up in an attribute.
 */
export type Text = string;
/**
 * Rich text: a plain string, or a list of inline nodes rendered in order by src/components/ui/Rich.tsx.
 */
export type Rich = string | [Inline, ...Inline[]];
/**
 * One inline node. Each object node has exactly one tag key (b, em, code, span, br, a, var, status, dim, flag, placeholder) plus the attributes that tag allows.
 */
export type Inline =
  | string
  | StrongNode
  | EmphasisNode
  | CodeNode
  | SpanNode
  | LineBreakNode
  | RouteLinkNode
  | UrlLinkNode
  | VariableNode
  | StatusNode
  | DimNode
  | FlagNode
  | PlaceholderNode;
/**
 * An internal link target: a route ID from src/routes.ts (home, community, architecture, architecture/<page>), optionally followed by #<anchor> from src/content/shared.ts anchors; or #<anchor> alone for the current page. Resolved to /… or /ko/… in code.
 */
export type RouteRef = string;
/**
 * An external link: an absolute https URL with no credentials.
 */
export type HttpsUrl = string;

/**
 * i18n/<locale>/home.json: the home page's copy in one locale — <title> and meta description, then the page's blocks. Editorial; code, package names, versions and dates are never here: rich text names them as vars the page supplies from src/content/shared.ts and the slots.
 */
export interface LocaleHomeV1 {
  $schema?: string;
  schemaVersion: 'locale-home-v1';
  locale: LocaleId;
  meta: {
    title: Text;
    description: Text;
  };
  hero: {
    eyebrow: Rich;
    title: Rich;
    lede: Rich;
    primaryCta: Text;
    secondaryCta: Text;
    proof: Rich;
    io: {
      caption: Text;
      footnote: Rich;
    };
  };
  problem: {
    eyebrow: Rich;
    title: Rich;
    lede: Rich;
    sourceLabel: Rich;
    sourceNote: Rich;
    redactedLabel: Text;
    destinations: {
      name: Rich;
      note: Rich;
    }[];
    kept: Text;
    counts: {
      value: Text;
      label: Rich;
    }[];
    remedy: Rich;
  };
  integrations: {
    eyebrow: Rich;
    title: Rich;
    lede: Rich;
    groups: {
      core: {
        title: Rich;
        lede: Rich;
        href: HttpsUrl;
      };
      adapters: {
        title: Rich;
        lede: Rich;
        href: HttpsUrl;
      };
      vault: {
        title: Rich;
        lede: Rich;
        href: HttpsUrl;
      };
    };
    runtimes: {
      browser: Text;
      node: Text;
      python: Text;
    };
    terms: {
      version: Text;
      registries: Text;
      core: Text;
      host: Text;
      tag: Text;
      install: Text;
    };
    statusLabels: {
      released: Text;
      alpha: Text;
      unpublished: Text;
    };
    notPublished: Text;
    cards: {
      core: {
        title: Rich;
        description: Rich;
        coverage: Rich;
      };
      wasm: {
        title: Rich;
        description: Rich;
        coverage: Rich;
      };
      cli: {
        title: Rich;
        description: Rich;
        coverage: Rich;
      };
      'web-stream': {
        title: Rich;
        description: Rich;
        coverage: Rich;
      };
      pino: {
        title: Rich;
        description: Rich;
        coverage: Rich;
      };
      otel: {
        title: Rich;
        description: Rich;
        coverage: Rich;
      };
      masking: {
        title: Rich;
        description: Rich;
        coverage: Rich;
      };
      'ai-context': {
        title: Rich;
        description: Rich;
        coverage: Rich;
      };
      mcp: {
        title: Rich;
        description: Rich;
        coverage: Rich;
      };
      logging: {
        title: Rich;
        description: Rich;
        coverage: Rich;
      };
      'otel-py': {
        title: Rich;
        description: Rich;
        coverage: Rich;
      };
      'masking-py': {
        title: Rich;
        description: Rich;
        coverage: Rich;
      };
      'vault-browser': {
        title: Rich;
        description: Rich;
        coverage: Rich;
      };
      'vault-node': {
        title: Rich;
        description: Rich;
        coverage: Rich;
      };
      'vault-server': {
        title: Rich;
        description: Rich;
        coverage: Rich;
      };
      'vault-py': {
        title: Rich;
        description: Rich;
        coverage: Rich;
      };
    };
    observed: Rich;
  };
  quickstart: {
    eyebrow: Rich;
    title: Rich;
    lede: Rich;
    tabsLabel: Text;
    rustNote: Rich;
    pinLabel: Text;
    pin: Rich;
    pinLatest: {
      same: Rich;
      moved: Rich;
    };
    why: {
      title: Rich;
      body: Rich;
    };
    expect: {
      title: Rich;
      body: Rich;
    };
  };
  playground: {
    eyebrow: Rich;
    title: Rich;
    lede: Rich;
    privacy: Rich;
    presetsLabel: Text;
    presets: {
      env: Text;
      log: Text;
      json: Text;
      header: Text;
      yaml: Text;
      prose: Text;
      pii: Text;
    };
    styleLabel: Text;
    piiLabel: Text;
    piiModes: {
      off: Text;
      global: Text;
      us: Text;
    };
    piiNote: Rich;
    inputLabel: Text;
    outputLabel: Text;
    clear: Text;
    reset: Text;
    loading: Text;
    loadFailed: Text;
    retry: Text;
    staleEngine: Text;
    reload: Text;
    engine: Rich;
    size: Rich;
    findingCount: {
      one: Rich;
      other: Rich;
    };
    findingsTitle: Rich;
    columns: {
      id: Text;
      type: Text;
      detector: Text;
      confidence: Text;
      action: Text;
      range: Text;
    };
    noFindings: Rich;
    errors: {
      INPUT_LIMIT_EXCEEDED: Text;
      FINDING_LIMIT_EXCEEDED: Text;
      UNPAIRED_SURROGATE: Text;
      default: Text;
    };
  };
  boundary: {
    eyebrow: Rich;
    title: Rich;
    lede: Rich;
    flowLabel: Text;
    flow: {
      key: Rich;
      title: Rich;
      description: Rich;
      core?: boolean;
    }[];
    pillars: {
      title: Rich;
      body: Rich;
    }[];
    links: Link[];
  };
  evidence: {
    eyebrow: Rich;
    title: Rich;
    lede: Rich;
    links: {
      title: Rich;
      body: Rich;
      go: Rich;
      href: HttpsUrl;
    }[];
    routing: {
      title: Rich;
      problemHeader: Text;
      startHeader: Text;
      rows: {
        problem: Rich;
        start: Rich;
      }[];
      note: Rich;
    };
    limits: {
      title: Rich;
      body: Rich[];
    };
  };
  final: {
    eyebrow: Rich;
    title: Rich;
    lede: Rich;
    primaryCta: Text;
    secondaryCta: Text;
  };
}
/**
 * <b>
 */
export interface StrongNode {
  b: Rich;
}
/**
 * <em>
 */
export interface EmphasisNode {
  em: Rich;
}
/**
 * <code>
 */
export interface CodeNode {
  code: Rich;
}
/**
 * <span> with one of the global type classes (src/style.css).
 */
export interface SpanNode {
  span: Rich;
  class: 'mono' | 'tiny' | 'small' | 'tiny mono';
}
/**
 * <br>: an authored line break (hero and other large headlines break at an explicit point per locale).
 */
export interface LineBreakNode {
  br: true;
}
/**
 * <a> to a page on this site, in the page's own locale.
 */
export interface RouteLinkNode {
  a: Rich;
  to: RouteRef;
}
/**
 * <a> to an external https URL.
 */
export interface UrlLinkNode {
  a: Rich;
  href: HttpsUrl;
}
/**
 * A value supplied by the page at render time: a slot (version, date, count) or a fragment the page composes. Never typed into prose (CONVENTIONS.md § Content slots).
 */
export interface VariableNode {
  var: string;
}
/**
 * A status chip (src/components/ui/StatusChip.tsx) inside a sentence.
 */
export interface StatusNode {
  status: Rich;
  tone: 'success' | 'warning' | 'danger' | 'info' | 'none';
}
/**
 * A dimmed span inside a code sample (RichCode's Dim).
 */
export interface DimNode {
  dim: Rich;
}
/**
 * A flagged span inside a code sample (RichCode's Flag).
 */
export interface FlagNode {
  flag: Rich;
}
/**
 * A typed placeholder chip (src/components/ui/PlaceholderChip.tsx), e.g. <SECRET_1>.
 */
export interface PlaceholderNode {
  placeholder: Rich;
}
/**
 * A labelled link: internal (to, a route ID) or external (href, an https URL). external marks it with ↗.
 */
export interface Link {
  label: Text;
  to?: RouteRef;
  href?: HttpsUrl;
  external?: boolean;
}
