/* eslint-disable */
/**
 * GENERATED by scripts/gen-data-types.mjs from schemas/release-v1.schema.json.
 * Do not edit: change the schema and run `npm run data:types`.
 */

/**
 * ISO 8601. A full date-time when a script recorded it; a calendar date when a maintainer read the source by hand and no finer time was recorded.
 */
export type Timestamp = string;
export type Registry = 'npm' | 'pypi' | 'crates';
/**
 * A full 40-character git commit SHA. Short SHAs are a display concern, never stored.
 */
export type GitRevision = string;
export type RepositoryName = string;
/**
 * fresh: read from its source at observedAt. stale: the last refresh could not read the source, so the previous value is kept with its ORIGINAL observedAt (and staleSince records when that refresh failed). A stale value is never presented as fresh.
 */
export type Freshness = 'fresh' | 'stale';
/**
 * sha256 of the exact payload bytes fetched from the source.
 */
export type Digest = string;

/**
 * data/release.json: what each package in data/integrations.json has actually published, read from its registry by scripts/refresh-slots.mjs, and the upstream feeds (redact-secret, redact-secret-adapters) cross-checked against it. Every record carries its own source, observation time, payload digest and freshness.
 */
export interface ReleaseV1 {
  $schema?: string;
  schemaVersion: 'release-v1';
  generatedAt: Timestamp;
  generator: 'scripts/refresh-slots.mjs';
  /**
   * Keyed by the package ids in data/integrations.json.
   */
  packages: {
    [k: string]: PackageRecord | undefined;
  };
  /**
   * The upstream feeds the refresh read, each pinned to the full commit it was fetched at. Package versions still come from the registries (`packages`); a feed is cross-checked against them and adds what only its owner knows. Optional so that a refresh without feeds stays valid; the committed file always has both.
   */
  feeds?: {
    product: ProductFeedRecord;
    adapters: AdaptersFeedRecord;
  };
}
export interface PackageRecord {
  source: RegistrySource;
  observedAt: Timestamp;
  freshness: Freshness;
  staleSince?: Timestamp;
  digest?: Digest;
  value: PackageValue;
  declared?: DeclaredVersion;
  mirrors?: Mirrors;
}
/**
 * A package registry document. `version` is the published version the value describes; `revision` is that version's git commit when the registry records one (npm gitHead).
 */
export interface RegistrySource {
  kind: 'registry';
  registry: Registry;
  package: string;
  url: string;
  version?: string;
  revision?: GitRevision;
  repository?: RepositoryName;
  /**
   * Files inside the published package the value was read from.
   */
  paths?: string[];
}
/**
 * What the page may say about the package. Either the published version (and, per registry, its tag, peers or requirements), or `unpublished: true` when the registry does not have it.
 */
export interface PackageValue {
  registry: Registry;
  name: string;
  version?: string;
  published?: string;
  /**
   * Where npm's `latest` dist-tag points.
   */
  latest?: string;
  /**
   * The npm dist-tag this page installs from.
   */
  tag?: string;
  peers?: {
    [k: string]: string | undefined;
  };
  dependencies?: {
    [k: string]: string | undefined;
  };
  /**
   * PyPI requires_dist.
   */
  requires?: string[];
  unpublished?: true;
}
/**
 * For a package its registry does not have: the version its repository declares, and where that was read.
 */
export interface DeclaredVersion {
  version: string;
  source: RepositorySource;
}
/**
 * Files read from a git repository at one full revision.
 */
export interface RepositorySource {
  kind: 'repository';
  repository: RepositoryName;
  revision: GitRevision;
  /**
   * The product release that revision is, if it is one.
   */
  release?: string;
  /**
   * Files at that revision the value was read from.
   */
  paths?: string[];
}
/**
 * The same package published to other registries under another name.
 */
export interface Mirrors {
  pypi?: MirrorRecord;
  crates?: MirrorRecord;
}
export interface MirrorRecord {
  source: RegistrySource;
  observedAt: Timestamp;
  freshness: Freshness;
  staleSince?: Timestamp;
  digest?: Digest;
  value: MirrorValue;
}
export interface MirrorValue {
  name: string;
  version: string;
  published?: string;
}
/**
 * redact-secret's site feed (docs/contracts/site-feed/v1/feed.json): the release identity and the support matrix the release ships, reduced to what the pages state.
 */
export interface ProductFeedRecord {
  source: RepositorySource;
  /**
   * The branch the commit was resolved from.
   */
  ref: string;
  observedAt: Timestamp;
  freshness: Freshness;
  staleSince?: Timestamp;
  /**
   * The feed's own schemaVersion; the refresh knows exactly one per feed and refuses any other.
   */
  schemaVersion: string;
  generatedAt: Timestamp;
  digest: Digest;
  schemaDigest: Digest;
  /**
   * Package ids (data/integrations.json) whose registry record agreed with the feed when it was read.
   */
  crossChecked: string[];
  value: ProductFeedValue;
}
export interface ProductFeedValue {
  release: ProductRelease;
  supportMatrix: SupportMatrixSummary;
}
export interface ProductRelease {
  version: string;
  tag: string;
  sourceRevision: GitRevision;
  verifiedOn: string;
}
/**
 * The pinned support matrix, as counts. `measuredProductVersion` is the product version the benchmark run measured and can be older than release.version; the pages show both. Counts only, never a score, rate or bound.
 */
export interface SupportMatrixSummary {
  benchmarksRevision: GitRevision;
  generatedAt: Timestamp;
  measuredProductVersion: string | null;
  measuredProductRevision: GitRevision | null;
  /**
   * True when the release's support-matrix drift gate ran against exactly this matrix.
   */
  gatedLatestRelease: boolean;
  families: number;
  providers: number;
  status: SupportStatusCounts;
  stableBasis: SupportStableBasisCounts;
  tiers: SupportTierCounts;
}
export interface SupportStatusCounts {
  stable: number;
  provisional: number;
  pending: number;
  unsupported: number;
}
export interface SupportStableBasisCounts {
  documented: number;
  empirical: number;
}
export interface SupportTierCounts {
  T0: number;
  T1: number;
  T2: number;
  T3: number;
}
/**
 * redact-secret-adapters' release feed (site-feed/v1/adapters.json) at the commit `ref` pointed to. mode `feed`: the feed was read, validated and cross-checked against the registry records. mode `registry-fallback`: the feed is not at that commit, so the registry records in `packages` are the only source, and `fallbackReason` says why.
 */
export interface AdaptersFeedRecord {
  source: RepositorySource;
  /**
   * The branch the commit was resolved from.
   */
  ref: string;
  observedAt: Timestamp;
  freshness: Freshness;
  staleSince?: Timestamp;
  /**
   * The feed's own schemaVersion; the refresh knows exactly one per feed and refuses any other.
   */
  schemaVersion?: string;
  generatedAt?: Timestamp;
  digest?: Digest;
  schemaDigest?: Digest;
  /**
   * Package ids (data/integrations.json) whose registry record agreed with the feed when it was read.
   */
  crossChecked?: string[];
  mode: 'feed' | 'registry-fallback';
  fallbackReason?: string;
  value?: AdaptersFeedValue;
}
export interface AdaptersFeedValue {
  packages: AdapterFeedPackage[];
}
export interface AdapterFeedPackage {
  id: string;
  ecosystem: 'npm' | 'pypi';
  name: string;
  version: string;
  channel: string;
  core: AdapterCoreRange;
}
/**
 * The core range the package declares and the two ends CI tests.
 */
export interface AdapterCoreRange {
  name: string;
  range: string;
  tested: TestedEnds;
}
export interface TestedEnds {
  lowest: string;
  highest: string;
}
