// Refreshes src/slots/release.json from the package registries.
//
// Run deliberately (`npm run slots:refresh`), review the diff, commit it.
// Never part of the build: a build uses only committed data
// (CONVENTIONS.md § Content slots). Reads package metadata only.
import { readFileSync, writeFileSync } from 'node:fs';

const catalogUrl = new URL('../src/slots/catalog.json', import.meta.url);
const releaseUrl = new URL('../src/slots/release.json', import.meta.url);
const catalog = JSON.parse(readFileSync(catalogUrl));
const today = new Date().toISOString().slice(0, 10);

async function getJson(url, attempts = 3) {
  const res = await fetch(url, { headers: { 'User-Agent': 'redact-secret-www slot refresh' } });
  if (res.status === 404) return undefined;
  if (res.status >= 500 && attempts > 1) {
    await new Promise((r) => setTimeout(r, 1000));
    return getJson(url, attempts - 1);
  }
  if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
  return res.json();
}

async function npm(name, tag = 'latest') {
  const doc = await getJson(`https://registry.npmjs.org/${name.replace('/', '%2f')}`);
  if (!doc) return undefined;
  const tags = doc['dist-tags'];
  const version = tags[tag] ?? tags.latest;
  const manifest = doc.versions[version];
  return {
    version,
    published: doc.time[version].slice(0, 10),
    latest: tags.latest,
    tag: tags[tag] ? tag : 'latest',
    peers: manifest.peerDependencies ?? {},
    dependencies: manifest.dependencies ?? {},
  };
}

async function pypi(name) {
  const doc = await getJson(`https://pypi.org/pypi/${name}/json`);
  if (!doc) return undefined;
  const version = doc.info.version;
  const files = doc.releases[version] ?? [];
  const requires = doc.info.requires_dist ?? [];
  return { version, published: files[0]?.upload_time?.slice(0, 10), requires };
}

async function crates(name) {
  const doc = await getJson(`https://crates.io/api/v1/crates/${name}`);
  if (!doc) return undefined;
  const latest = doc.versions.find((v) => v.num === doc.crate.max_version);
  return { version: latest.num, published: latest.created_at.slice(0, 10) };
}

const fetchers = { npm, pypi, crates };

const packages = {};
for (const [id, entry] of Object.entries(catalog.packages)) {
  const primary = await fetchers[entry.registry](entry.name, entry.tag);
  const record = { registry: entry.registry, name: entry.name };
  if (primary) Object.assign(record, primary);
  else record.unpublished = entry.unpublishedVersion ?? true;
  for (const also of entry.also ?? []) {
    const found = await fetchers[also.registry](also.name);
    if (found) record[also.registry] = { name: also.name, version: found.version, published: found.published };
  }
  packages[id] = record;
  console.log(id.padEnd(20), record.unpublished ? 'unpublished' : `${record.version} (${record.published})`);
}

const core = packages.core;
const cli = packages.cli;
const release = {
  $comment: 'Generated by scripts/refresh-slots.mjs from the registries. Review the diff before committing.',
  observedAt: today,
  core: {
    observedAt: today,
    npm: core.version,
    npmLatest: core.latest,
    pypi: core.pypi?.version,
    crate: cli?.version,
  },
  packages,
};

writeFileSync(releaseUrl, `${JSON.stringify(release, null, 2)}\n`);
console.log(`wrote ${releaseUrl.pathname}`);
